[default_session]

[[session]]
name = "System config"
path = "~/system-config"
startup_command = "vim"

[[session]]
name = "Dotfiles"
path = "~/system-config/dotfiles"
startup_command = "vim"

[[session]]
name = "Work"
path = "~/projects/work"

[[session]]
name = "Nvim Config"
path = "~/system-config/dotfiles/nvim"
startup_command = "vim"

[[session]]
name = "Home"
path = "~/"

[[session]]
name = "New Project"
path = "~/projects/personal"
startup_command = "new_project"
